### ISSUE TITLE
HP above 10 generates an error

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#4]
It appears if you tag an aspect with more than 10 hp, it causes a "General Error" with the number I input. Example below.

```
    - name: Some Meta Name
      text: A really really meta description.
      rules:
       HP Pool Modifier: "+11"
```

**Comment by zinic** [comment]
This is a bit of a game design question I've been mulling over for a while.

The option generator only creates options for the rules up to a certain point:

```xml
<rule name="Presence Modifier" category="all">
    <formula ref="Normal Progression">
    </formula>

    <option name="+{range_value}" range="1,6"/>

    <text>
        **Note:** this component may not be used for attack rolls.
    </text>
</rule>
```

The snippet above will generate options starting at 1 and ending at 6 (inclusive). This means that after a `+6` there are no further options to source.

The real question here is: do we restrict just how much a single aspect can contain and if so, does it even make sense to? Food for thought but since aspects are usually designed at char creation, this is where it would have the most impact.

More thinking here required.

**Comment by zinic** [comment]
Another thing I was thinking about is that I really don't want players to try and extrapolate the formula from the given options. In other words I don't want someone to notice a linear progression and simply assume that they can extend the rule beyond the options presented. Balance considerations for such things are likely to paralyze further development.

The system should support customization to a certain point - not infinitely.

**Comment by Sedohr** [comment]
I think this is good for now. Maybe in the future we may want to change this restriction per campaign, for example there might be a campaign where it's normal to have high HP values and in that game it might make sense to increase the limit. Otherwise maybe a way for the gm to override these rules if needed, but for now I'm fine with working under the same limitations and just branching out more aspects as needed.
